node {
       stage('Checkout') {
            git url:'https://github.com/prakhasaxena19/pareshan_ho_gye.git', branch:'master'
        }

        stage('Build') {
            sh 'mvn -v'
            sh 'java -version'
            sh 'mvn clean'
            sh 'mvn package'

             }

}
