node {
       stage('Checkout') {
            git url:'https://github.com/prakhasaxena19/pareshan_ho_gye.git', branch:'master'
        }

        stage('Build') {
           build 'Pipe_2'

             }

}
